epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"

rnn_hidden_dim: 128  # Size of hidden state for default rnn agent
use_cuda: False # Use gpu by default unless it isn't available

name: "separate_actor_critic"